add LoadTokenizerFromHuggingFace function to load tokenizer directly …
daulet/tokenizers pull request #27
Opened 2024-10-25 08:23 UTC by berkayersoyy

| Benchmark            | benchmarks/eafe2ce1db50dcd78b3b7157bf2c669109f4e322.txt | benchmarks/867b67eeade51e570d5150cebddab679b855e885.txt | Change               |
|----------------------|--------------------------------------------------------|--------------------------------------------------------|----------------------|
| **sec/op**           |                                                        |                                                        |                      |
| EncodeNTimes-10      | 12.75µ ± 2%                                            | 12.60µ ± 1%                                            | -1.18% (p=0.015 n=6) |
| EncodeNChars-10      | 0.3629n ± 19%                                          | 0.3589n ± 8%                                           | ~ (p=1.000 n=6)      |
| DecodeNTimes-10      | 4.433µ ± 1%                                            | 4.481µ ± 1%                                            | +1.08% (p=0.011 n=6) |
| DecodeNTokens-10     | 660.5n ± 2%                                            | 662.0n ± 5%                                            | ~ (p=0.485 n=6)      |
| Geomean              | 341.2n                                                 | 340.3n                                                 | -0.25%               |

| Benchmark            | benchmarks/eafe2ce1db50dcd78b3b7157bf2c669109f4e322.txt | benchmarks/867b67eeade51e570d5150cebddab679b855e885.txt | Change               |
|----------------------|--------------------------------------------------------|--------------------------------------------------------|----------------------|
| **B/op**             |                                                        |                                                        |                      |
| EncodeNTimes-10      | 232.0 ± 0%                                             | 232.0 ± 0%                                             | ~ (p=1.000 n=6)¹     |
| EncodeNChars-10      | 0.000 ± 0%                                             | 0.000 ± 0%                                             | ~ (p=1.000 n=6)¹     |
| DecodeNTimes-10      | 96.00 ± 0%                                             | 96.00 ± 0%                                             | ~ (p=1.000 n=6)¹     |
| DecodeNTokens-10     | 7.000 ± 0%                                             | 7.000 ± 0%                                             | ~ (p=1.000 n=6)¹     |
| Geomean              |                                                        |                                                        | +0.00%²              |

| Benchmark            | benchmarks/eafe2ce1db50dcd78b3b7157bf2c669109f4e322.txt | benchmarks/867b67eeade51e570d5150cebddab679b855e885.txt | Change               |
|----------------------|--------------------------------------------------------|--------------------------------------------------------|----------------------|
| **allocs/op**        |                                                        |                                                        |                      |
| EncodeNTimes-10      | 12.00 ± 0%                                             | 12.00 ± 0%                                             | ~ (p=1.000 n=6)¹     |
| EncodeNChars-10      | 0.000 ± 0%                                             | 0.000 ± 0%                                             | ~ (p=1.000 n=6)¹     |
| DecodeNTimes-10      | 3.000 ± 0%                                             | 3.000 ± 0%                                             | ~ (p=1.000 n=6)¹     |
| DecodeNTokens-10     | 0.000 ± 0%                                             | 0.000 ± 0%                                             | ~ (p=1.000 n=6)¹     |
| Geomean              |                                                        |                                                        | +0.00%²              |

¹ All samples are equal  
² Summaries must be >0 to compute geomean

2024-10-28 08:21 UTC, berkayersoyy commented
I added a few things so that the tokenizer can be loaded directly from huggingface, if you could review it that would be great @daulet 🙏

2024-10-28 18:04 UTC, daulet commented on tokenizer.go
> +	errChan := make(chan error, len(tokenizerFiles))
let's use unbuffered channel: https://github.com/uber-go/guide/blob/master/style.md#channel-size-is-one-or-none

using buffered channels tends to hide concurrency issues if present

2024-10-28 18:06 UTC, daulet commented on tokenizer.go
> +					logMutex.Lock()
i dont believe you need this mutex at all

> fmt::print provides the same thread-safety guarantees as the underlying system API which is fwrite (or WriteConsoleW when writing to the console on Windows) for FILE* overloads. These APIs are normally thread-safe

2024-10-28 18:09 UTC, daulet commented on tokenizer.go
> +	return tokenizer, nil
```suggestion
	return FromFile(tokenizerPath)
```

2024-10-28 18:09 UTC, daulet commented on tokenizer.go
> +	close(errChan)
nit: name this `errCh`

2024-10-28 18:10 UTC, daulet commented on tokenizer.go
> +		if downloadErr != nil {
looks like all errors sent to the channel are non-nil so check is redundant. Just looking out for minimal indentation

2024-10-28 18:11 UTC, daulet reviewed
Thank you for your contribution! In principle looks good, let's just iron out concurrency stuff.

2024-10-29 15:33 UTC, berkayersoyy commented
I made the changes you mentioned, can you review them again? 🙏

2024-11-05 01:04 UTC, daulet commented on tokenizer.go
> +func FromPretrained(modelID string, destination, authToken *string) (*Tokenizer, error) {
let's add a test to exercise default and optional params, e.g. with and without optional auth token

2024-11-05 01:29 UTC, daulet commented
@berkayersoyy I've made few changes instead of PR comments, lets just add tests and we are good to go

2024-11-05 07:15 UTC, berkayersoyy commented
looks good 🙏 , I added the tests @daulet

2024-11-05 16:19 UTC, daulet commented on tokenizer_test.go
> +	"github.com/daulet/tokenizers"
this shouldn't be necessary, you are in the same package

2024-11-05 16:21 UTC, daulet commented on tokenizer_test.go
> -	"github.com/daulet/tokenizers"
keep it in this order

2024-11-05 16:22 UTC, daulet commented on tokenizer_test.go
> +		if tokenizer != nil {
redundant check

2024-11-05 16:23 UTC, daulet commented on tokenizer_test.go
> +			t.Error("expected error with invalid auth token, got nil")
rewrite these in table test format, where expected error, token are parameters, but the test body is the same

2024-11-05 16:24 UTC, daulet commented on tokenizer_test.go
> +			t.Error("expected error with invalid auth token, got nil")
https://go.dev/wiki/TableDrivenTests

2024-11-05 16:24 UTC, daulet commented on tokenizer_test.go
> +				t.Errorf("unexpected error: %v", err)
If you want Error + return, then probably just use `Fatalf`

2024-11-05 16:26 UTC, daulet commented on tokenizer_test.go
> +func mockHuggingFaceServer(t *testing.T) *httptest.Server {
i appreciate writing a mock for it, but why not just use the actual HF endpoint? would be less effort to maintain

2024-11-07 01:46 UTC, daulet requested changes
left comments

2024-11-07 07:12 UTC, berkayersoyy commented
updated the tests 🙏 @daulet

2024-11-07 21:04 UTC, daulet approved these changes

2024-11-07 21:05 UTC, merged

2024-11-07 21:05 UTC, daulet commented
Thank you @berkayersoyy for your contribution!